#!/usr/bin/with-contenv bash

if [ -n "${UMASK_SET}" ] && [ -z "${UMASK}" ]; then
  echo -e "You are using a legacy method of defining umask\nplease update your environment variable from UMASK_SET to UMASK\nto keep the functionality after July 2021"
  umask ${UMASK_SET}
fi

if pgrep -f "[n]ginx:" > /dev/null; then
  echo "Zombie nginx processes detected, sending SIGTERM"
  pkill -ef [n]ginx:
  sleep 1
fi

if pgrep -f "[n]ginx:" > /dev/null; then
  echo "Zombie nginx processes still active, sending SIGKILL"
  pkill -9 -ef [n]ginx:
  sleep 1
fi

exec /usr/sbin/nginx -c /config/nginx/nginx.conf