#!/usr/bin/with-contenv bash

# make our folders and links
mkdir -p /config/nginx
mkdir -p /config/www/static
mkdir -p /config/log/nginx/
mkdir -p /opt/data


#copy default configs

if [ ! -e "/config/nginx/nginx.conf" ]; then
  cp -R /defaults/nginx /config/
fi

if [ ! -e "/config/www/static/stat.xsl" ]; then
  cp -R /defaults/www /config/
fi

# logfiles needed by nginx
[[ ! -f /config/log/nginx/error.log ]] && \
	touch /config/log/nginx/error.log
[[ ! -f /config/log/nginx/access.log ]] && \
	touch /config/log/nginx/access.log


# permissions
chown -R abc:abc /config
chmod -R 770 /config
chmod -R +r /config

chown -R abc:abc /opt/data
chmod -R 770 /opt/data
chmod -R +r /opt/data